from datetime import datetime
from enum import Enum as PyEnum
from sqlalchemy import (
    String, Integer, Boolean, Float, DateTime,
    ForeignKey, Text, JSON, Enum
)
from sqlalchemy.orm import Mapped, mapped_column, relationship
from app.db.database import Base


# ──────────────────────────────────────────
# Enums
# ──────────────────────────────────────────

class AgeGroup(str, PyEnum):
    JUNIOR       = "junior"        # 8-11
    INTERMEDIATE = "intermediate"  # 12-14
    SENIOR       = "senior"        # 15-17


class LessonStatus(str, PyEnum):
    NOT_STARTED = "not_started"
    IN_PROGRESS = "in_progress"
    COMPLETED   = "completed"


# ──────────────────────────────────────────
# User
# ──────────────────────────────────────────

class User(Base):
    __tablename__ = "users"

    id:           Mapped[int]      = mapped_column(Integer, primary_key=True, index=True)
    name:         Mapped[str]      = mapped_column(String(100))
    email:        Mapped[str]      = mapped_column(String(200), unique=True, index=True)
    hashed_password: Mapped[str]   = mapped_column(String(200))
    age:          Mapped[int]      = mapped_column(Integer)
    age_group:    Mapped[AgeGroup] = mapped_column(Enum(AgeGroup))
    coins:        Mapped[int]      = mapped_column(Integer, default=0)
    xp:           Mapped[int]      = mapped_column(Integer, default=0)
    is_parent:    Mapped[bool]     = mapped_column(Boolean, default=False)
    parent_id:    Mapped[int|None] = mapped_column(Integer, ForeignKey("users.id"), nullable=True)
    created_at:   Mapped[datetime] = mapped_column(DateTime, default=datetime.utcnow)

    # Relationships
    lesson_progress: Mapped[list["LessonProgress"]] = relationship(back_populates="user")
    children:        Mapped[list["User"]]            = relationship("User", foreign_keys=[parent_id])


# ──────────────────────────────────────────
# Lesson
# ──────────────────────────────────────────

class Lesson(Base):
    __tablename__ = "lessons"

    id:           Mapped[int]      = mapped_column(Integer, primary_key=True, index=True)
    title:        Mapped[str]      = mapped_column(String(200))
    description:  Mapped[str]      = mapped_column(Text)
    age_group:    Mapped[AgeGroup] = mapped_column(Enum(AgeGroup), index=True)
    topic:        Mapped[str]      = mapped_column(String(100))   # e.g. "savings", "budget", "banking"
    order_index:  Mapped[int]      = mapped_column(Integer)       # lesson order within age group
    xp_reward:    Mapped[int]      = mapped_column(Integer, default=50)
    coin_reward:  Mapped[int]      = mapped_column(Integer, default=10)
    # Lesson content stored as JSON (generated by Gemini or static)
    content:      Mapped[dict]     = mapped_column(JSON)
    created_at:   Mapped[datetime] = mapped_column(DateTime, default=datetime.utcnow)

    # Relationships
    quiz:            Mapped["Quiz|None"]          = relationship(back_populates="lesson", uselist=False)
    lesson_progress: Mapped[list["LessonProgress"]] = relationship(back_populates="lesson")


# ──────────────────────────────────────────
# Quiz
# ──────────────────────────────────────────

class Quiz(Base):
    __tablename__ = "quizzes"

    id:        Mapped[int]  = mapped_column(Integer, primary_key=True, index=True)
    lesson_id: Mapped[int]  = mapped_column(Integer, ForeignKey("lessons.id"), unique=True)
    # questions: list of {question, options: [], correct_index, explanation}
    questions: Mapped[list] = mapped_column(JSON)

    lesson: Mapped["Lesson"] = relationship(back_populates="quiz")


# ──────────────────────────────────────────
# Lesson Progress
# ──────────────────────────────────────────

class LessonProgress(Base):
    __tablename__ = "lesson_progress"

    id:           Mapped[int]          = mapped_column(Integer, primary_key=True, index=True)
    user_id:      Mapped[int]          = mapped_column(Integer, ForeignKey("users.id"))
    lesson_id:    Mapped[int]          = mapped_column(Integer, ForeignKey("lessons.id"))
    status:       Mapped[LessonStatus] = mapped_column(Enum(LessonStatus), default=LessonStatus.NOT_STARTED)
    quiz_score:   Mapped[float|None]   = mapped_column(Float, nullable=True)   # 0.0 - 1.0
    completed_at: Mapped[datetime|None]= mapped_column(DateTime, nullable=True)

    user:   Mapped["User"]   = relationship(back_populates="lesson_progress")
    lesson: Mapped["Lesson"] = relationship(back_populates="lesson_progress")